### ISSUE TITLE
TCP 设置心跳不生效？

### ISSUE THREAD

**Issue by lpz0715** [CWTakiku/NettyIM#12]
TCP模式 设置完心跳，一直不发送，Websocket 没有问题

**Comment by CWTakiku** [comment]
能否发一下你的配置截图

**Comment by lpz0715** [comment]
> 能否获得您的配置截图

我用demo试了下，打开test下的服务就可以正常发送心跳，连接我自己后台、以及测试工具建立的服务，查看日志都没有心跳发送，是对服务端写法有要求吗？

**Comment by CWTakiku** [comment]
首先检测发送端是否有设置心跳包，是否有发送日志打印，其次检测后台是否没有正确解析到你的心跳包数据
